name = "Trebuchet"
uuid = "98b73d46-197d-11e9-11eb-69a6ff759d3a"
authors = ["Roboneet <neethumariyajoy@gmail.com>"]
version = "0.1.0"

[deps]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
JSExpr = "97c1335a-c9c5-57fe-bc5d-ec35cebe8660"
WebIO = "0f1e0344-ec1d-5b48-a673-e5cf874b6c29"
