name = "Trebuchet"
uuid = "98b73d46-197d-11e9-11eb-69a6ff759d3a"
version = "0.2.1"

[deps]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
JSExpr = "97c1335a-c9c5-57fe-bc5d-ec35cebe8660"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
WebIO = "0f1e0344-ec1d-5b48-a673-e5cf874b6c29"

[compat]
JSExpr = "0.5"
julia = "1"
